"""Baseline evaluation report generator.

This module wires the complete evaluation pipeline for classical baselines:

    processed parquet
        → target (compute_target)
        → log returns (log_returns)
        → realized variance (for HAR-RV)
        → walk-forward test splits (walk_forward_splits)
        → EWMA, GARCH(1,1), HAR-RV forecasts (identical folds)
        → canonical metrics (qlike, rmse, mae)
        → per-asset report table (baseline_eval.md + baseline_metrics.csv)

Design:
    ``generate_baseline_report`` is a pure library function (no side effects
    beyond writing the two output files).  It is callable from tests with a
    tiny fixture and from a CLI/script with the full 5-asset universe.

    All three baselines are scored on IDENTICAL walk-forward folds per asset
    (splits are computed once per asset and shared across models — T-02-09).

    GARCH fallback counts are recorded per asset for transparency.

Unit contract (enforced by tests/unit/test_report_e2e.py and
               tests/unit/test_report_baselines.py):
    - Metrics are computed ONLY on walk-forward test indices (not in-sample).
    - NaN and zero target rows are dropped before scoring (Pitfall 4).
    - Forecasts are in decimal variance units (same as compute_target output).
    - QLIKE is fed variance vs variance (not std dev).
    - All three models score on the SAME splits.

Output:
    {output_dir}/baseline_eval.md  — Markdown table, one row per (asset, model)
    {output_dir}/baseline_metrics.csv — machine-readable, one row per (asset, model)

References:
    - Patton, A.J. (2011). Volatility forecast comparison using imperfect
      volatility proxies. Journal of Econometrics, 160(1), 246–256.
    - J.P. Morgan / Reuters (1996). RiskMetrics Technical Document.
    - Corsi, F. (2009). A Simple Approximate Long-Memory Model of Realized
      Volatility. Journal of Financial Econometrics, 7(2), 174–196.
"""

from __future__ import annotations

import csv
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

from volforecast import config as cfg
from volforecast.eval.harness import walk_forward_splits
from volforecast.eval.metrics import mae, qlike, rmse
from volforecast.features.estimators import log_returns, realized_var
from volforecast.features.target import HORIZON, compute_target
from volforecast.models.ewma import EWMA
from volforecast.models.garch import GARCH
from volforecast.models.har_rv import HARRV

log = logging.getLogger(__name__)

# Report section header — explains units and protocol once
_REPORT_HEADER = """\
# Baseline Evaluation Report: EWMA + GARCH(1,1) + HAR-RV

**Generated by:** `volforecast.reports.baseline.generate_baseline_report`

**Unit convention:**
- Metrics are computed in daily decimal variance units (e.g., ~1e-4 for typical daily equity).
- QLIKE uses the Patton (2011) variance form: `mean(ratio - ln(ratio) - 1)` where
  `ratio = realized_var / forecast_var`.  QLIKE = 0 at a perfect forecast.
- RMSE and MAE are also in daily decimal variance units.
- Volatility (standard deviation) is `sqrt(variance)`; no annualization inside the pipeline.

**Evaluation protocol:**
- Walk-forward expanding window: min_train=252 (≈1 year), step=21 (≈1 month).
- All three baselines (EWMA, GARCH, HAR-RV) are scored on IDENTICAL folds per asset.
- Metrics are computed only on walk-forward **test** indices — no in-sample leakage.
- NaN target rows (final `horizon` rows per series) are dropped before scoring.
- Zero target rows (identical consecutive closes — yfinance adjusted-close artifact)
  are also dropped (a zero realized variance causes QLIKE = +inf via log(0)).
- EWMA lambda = 0.94 (RiskMetrics daily, J.P. Morgan 1994).
- GARCH(1,1): fitted on 100x scaled returns (rescale=False), refitted monthly.
  Fallback: previous window params → EWMA. Fallback counts are reported per asset.
- HAR-RV: Corsi (2009) OLS on rv_d/rv_w(5-day mean)/rv_m(22-day mean), refitted monthly.

---

"""


@dataclass
class _AssetResult:
    """Intermediate result for one (asset, model) walk-forward evaluation."""

    slug: str
    model: str
    n_forecasts: int
    rmse_val: float
    mae_val: float
    qlike_val: float
    garch_fallbacks: int = field(default=0)


def generate_baseline_report(
    assets: list[dict[str, Any]],
    output_dir: Path,
    min_train: int = 252,
    step: int = 21,
    data_root: Path | None = None,
) -> Path:
    """Run EWMA + GARCH + HAR-RV walk-forward evaluation on identical folds.

    For each asset in ``assets``:
    1. Load the processed parquet from ``config.processed_path(asset, data_root)``.
    2. Compute log returns, the next-day realized-variance target, and daily RV.
    3. Generate one-step-ahead EWMA forecasts (full series, no per-fold refit).
    4. Generate GARCH(1,1) walk-forward forecasts (monthly refit).
    5. Generate HAR-RV walk-forward forecasts (per-step refit, cheap OLS).
    6. Iterate ``walk_forward_splits`` ONCE per asset; score all three models
       on the SAME test indices (identical folds — T-02-09 guard).
    7. Drop pairs where the target is NaN or zero (Pitfall 4).
    8. Score each model's collected pairs with ``qlike``, ``rmse``, ``mae``.

    Both output files are written atomically (write to tmp name, rename).

    Args:
        assets:     List of asset dicts with keys ``symbol`` and ``asset_class``.
        output_dir: Directory to write ``baseline_eval.md`` and
                    ``baseline_metrics.csv``.  Created if it does not exist.
        min_train:  Minimum training window size for the harness.  Default 252.
        step:       Walk-forward step and test window size.  Default 21.
        data_root:  Data root directory passed to ``config.processed_path``.
                    If None, defaults to ``config.project_root() / "data"``.

    Returns:
        Path to the written ``baseline_eval.md``.

    Raises:
        FileNotFoundError: If a processed parquet does not exist for an asset.
        ValueError: If no valid forecast/target pairs are found for any asset.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results: list[_AssetResult] = []

    for asset in assets:
        slug = cfg.symbol_slug(asset["symbol"])
        parquet_path = cfg.processed_path(asset, data_root)

        log.info("Evaluating all baselines for %s (%s)", slug, parquet_path)

        df = pd.read_parquet(parquet_path)
        close = df["close"].rename(slug)

        # Compute log returns and target (decimal variance proxy)
        lr = log_returns(close)
        target = compute_target(close, horizon=HORIZON)

        # Daily realized variance for HAR-RV (squared log returns)
        rv_daily = realized_var(lr, window=1)  # RV(1) = r^2 for daily

        n = len(close)

        # ------------------------------------------------------------------ #
        # Pre-compute EWMA forecast path (stateless — one call)
        # ------------------------------------------------------------------ #
        ewma_model = EWMA()
        ewma_forecasts = ewma_model.forecast_path(lr)

        # ------------------------------------------------------------------ #
        # Pre-compute GARCH and HAR-RV forecast paths (walk-forward)
        # ------------------------------------------------------------------ #
        garch_model = GARCH(min_train=min_train, step=step)
        log.info("  Running GARCH walk-forward for %s ...", slug)
        garch_forecasts = garch_model.forecast_path(lr)

        har_model = HARRV(min_train=min_train, step=step)
        log.info("  Running HAR-RV walk-forward for %s ...", slug)
        har_forecasts = har_model.forecast_path(rv_daily)

        # ------------------------------------------------------------------ #
        # Score all three models on IDENTICAL walk-forward folds
        # ------------------------------------------------------------------ #
        ewma_fc_list: list[float] = []
        garch_fc_list: list[float] = []
        har_fc_list: list[float] = []
        targets_list: list[float] = []

        for split in walk_forward_splits(n, min_train=min_train, step=step, horizon=HORIZON):
            test_tgt = target.iloc[split.test_idx]
            # Pitfall 4: drop NaN and exact-zero targets (QLIKE = +inf for zero)
            valid_mask = test_tgt.notna() & (test_tgt > 0.0)
            if not valid_mask.any():
                continue

            tgt_valid = test_tgt[valid_mask]
            ewma_valid = ewma_forecasts.iloc[split.test_idx][valid_mask]
            garch_valid = garch_forecasts.iloc[split.test_idx][valid_mask]
            har_valid = har_forecasts.iloc[split.test_idx][valid_mask]

            targets_list.extend(tgt_valid.tolist())
            ewma_fc_list.extend(ewma_valid.tolist())
            garch_fc_list.extend(garch_valid.tolist())
            har_fc_list.extend(har_valid.tolist())

        if not targets_list:
            log.warning(
                "Asset %s: no valid forecast/target pairs "
                "(series length=%d, min_train=%d) — skipping",
                slug,
                n,
                min_train,
            )
            continue

        n_fc = len(targets_list)

        # Score EWMA
        results.append(
            _AssetResult(
                slug=slug,
                model="EWMA",
                n_forecasts=n_fc,
                rmse_val=rmse(targets_list, ewma_fc_list),
                mae_val=mae(targets_list, ewma_fc_list),
                qlike_val=qlike(targets_list, ewma_fc_list),
            )
        )

        # Score GARCH
        results.append(
            _AssetResult(
                slug=slug,
                model="GARCH",
                n_forecasts=n_fc,
                rmse_val=rmse(targets_list, garch_fc_list),
                mae_val=mae(targets_list, garch_fc_list),
                qlike_val=qlike(targets_list, garch_fc_list),
                garch_fallbacks=garch_model.fallback_count,
            )
        )

        # Score HAR-RV
        results.append(
            _AssetResult(
                slug=slug,
                model="HAR",
                n_forecasts=n_fc,
                rmse_val=rmse(targets_list, har_fc_list),
                mae_val=mae(targets_list, har_fc_list),
                qlike_val=qlike(targets_list, har_fc_list),
            )
        )

        log.info(
            "%s  EWMA RMSE=%.4e  GARCH RMSE=%.4e  HAR RMSE=%.4e  n=%d  garch_fallbacks=%d",
            slug,
            results[-3].rmse_val,
            results[-2].rmse_val,
            results[-1].rmse_val,
            n_fc,
            garch_model.fallback_count,
        )

    if not results:
        raise ValueError(
            "No assets produced valid results.  Check that series are long enough "
            f"for min_train={min_train} and step={step}."
        )

    # ------------------------------------------------------------------ #
    # Write Markdown table
    # ------------------------------------------------------------------ #
    md_path = output_dir / "baseline_eval.md"
    _write_markdown(results, md_path, min_train=min_train, step=step)

    # ------------------------------------------------------------------ #
    # Write CSV
    # ------------------------------------------------------------------ #
    csv_path = output_dir / "baseline_metrics.csv"
    _write_csv(results, csv_path)

    log.info("Baseline report written to %s", output_dir)
    return md_path


def _write_markdown(
    results: list[_AssetResult],
    path: Path,
    min_train: int = 252,
    step: int = 21,
) -> None:
    """Write the per-asset three-baseline metrics table as a Markdown file."""
    lines = [_REPORT_HEADER]
    lines.append("## Per-Asset Metrics: EWMA vs GARCH(1,1) vs HAR-RV\n")
    lines.append("\n")
    lines.append("| Asset | Model | N Forecasts | RMSE | MAE | QLIKE | GARCH Fallbacks |\n")
    lines.append("|-------|-------|-------------|------|-----|-------|----------------|\n")

    # Group by asset for readable output
    # Collect unique slugs in order
    slugs_seen: list[str] = []
    slug_rows: dict[str, list[_AssetResult]] = {}
    for r in results:
        if r.slug not in slug_rows:
            slugs_seen.append(r.slug)
            slug_rows[r.slug] = []
        slug_rows[r.slug].append(r)

    for slug in slugs_seen:
        for r in slug_rows[slug]:
            fallbacks = r.garch_fallbacks if r.model == "GARCH" else "-"
            lines.append(
                f"| {r.slug} | {r.model} | {r.n_forecasts:,} "
                f"| {r.rmse_val:.6e} | {r.mae_val:.6e} | {r.qlike_val:.6f} "
                f"| {fallbacks} |\n"
            )

    lines.append("\n")
    lines.append("## Notes\n")
    lines.append("\n")
    lines.append(
        "- **EWMA** (RiskMetrics, λ=0.94): Deterministic exponential smoothing.  "
        "No fitting required.  Benchmark for the simplest possible baseline.\n"
    )
    lines.append(
        "- **GARCH(1,1)**: Time-varying volatility clustering.  Fitted on 100× scaled "
        "returns (rescale=False), refitted monthly.  "
        "Convergence + stationarity (α+β<1) asserted on every refit.  "
        "GARCH fallback count = number of windows where the optimizer failed or produced "
        "non-stationary params (fallback: previous window params → EWMA).\n"
    )
    lines.append(
        "- **HAR-RV** (Corsi 2009): Heterogeneous Autoregressive model on realized variance.  "
        "OLS on lagged daily/weekly(5-day mean)/monthly(22-day mean) RV.  "
        "Refitted monthly.  Captures multi-scale volatility persistence.\n"
    )
    lines.append(
        "- All three models are scored on **identical** walk-forward folds per asset "
        f"(min_train={min_train}, step={step}).  "
        "Direct comparison is fair.\n"
    )
    lines.append("\n")
    lines.append("---\n")
    lines.append(
        "*Metrics: daily decimal variance units. "
        "QLIKE = 0 at perfect forecast. "
        "Lower is better for all three metrics.*\n"
    )

    # Atomic write
    tmp = path.with_suffix(".tmp")
    tmp.write_text("".join(lines), encoding="utf-8")
    tmp.replace(path)


def _write_csv(results: list[_AssetResult], path: Path) -> None:
    """Write the per-asset metrics as a CSV file."""
    fieldnames = [
        "asset",
        "model",
        "n_forecasts",
        "rmse",
        "mae",
        "qlike",
        "garch_fallbacks",
    ]

    # Atomic write
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            writer.writerow(
                {
                    "asset": r.slug,
                    "model": r.model,
                    "n_forecasts": r.n_forecasts,
                    "rmse": f"{r.rmse_val:.10e}",
                    "mae": f"{r.mae_val:.10e}",
                    "qlike": f"{r.qlike_val:.10f}",
                    "garch_fallbacks": r.garch_fallbacks if r.model == "GARCH" else "",
                }
            )
    tmp.replace(path)
