"""Baseline evaluation report generator.

This module wires the complete evaluation pipeline for classical baselines:

    processed parquet
        → target (compute_target)
        → log returns (log_returns)
        → EWMA one-step-ahead forecasts (EWMA.forecast_path)
        → walk-forward test splits (walk_forward_splits)
        → canonical metrics (qlike, rmse, mae)
        → per-asset report table (baseline_eval.md + baseline_metrics.csv)

Design:
    ``generate_baseline_report`` is a pure library function (no side effects
    beyond writing the two output files).  It is callable from tests with a
    tiny fixture and from a CLI/script with the full 5-asset universe.  Plan
    02-03 will extend it to add GARCH and HAR-RV columns without changing the
    signature or the Markdown table structure.

Unit contract (enforced by tests/unit/test_report_e2e.py):
    - Metrics are computed ONLY on walk-forward test indices (not in-sample).
    - NaN target rows (end-of-series) are dropped before scoring — Pitfall 4:
      never fill with zero.  A zero target corrupts QLIKE.
    - Zero target rows are also dropped (identical consecutive closes in yfinance
      adjusted-close data — a data artifact; target = sq(log return) = 0 causes
      QLIKE = +inf via log(0)).
    - Forecasts are in decimal variance units (same as compute_target output).
    - QLIKE is fed variance vs variance (not std dev).

Output:
    {output_dir}/baseline_eval.md  — Markdown table, one row per asset
    {output_dir}/baseline_metrics.csv — machine-readable, one row per (asset, model)

References:
    - Patton, A.J. (2011). Volatility forecast comparison using imperfect
      volatility proxies. Journal of Econometrics, 160(1), 246–256.
    - J.P. Morgan / Reuters (1996). RiskMetrics Technical Document.
"""

from __future__ import annotations

import csv
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from volforecast import config as cfg
from volforecast.eval.harness import walk_forward_splits
from volforecast.eval.metrics import mae, qlike, rmse
from volforecast.features.estimators import log_returns
from volforecast.features.target import HORIZON, compute_target
from volforecast.models.ewma import EWMA

log = logging.getLogger(__name__)

# Report section header — explains units once, not per row
_REPORT_HEADER = """\
# EWMA Baseline Evaluation Report

**Generated by:** `volforecast.reports.baseline.generate_baseline_report`

**Unit convention:**
- Metrics are computed in daily decimal variance units (e.g., ~1e-4 for typical daily equity).
- QLIKE uses the Patton (2011) variance form: `mean(ratio - ln(ratio) - 1)` where
  `ratio = realized_var / forecast_var`.  QLIKE = 0 at a perfect forecast.
- RMSE and MAE are also in daily decimal variance units.
- Volatility (standard deviation) is `sqrt(variance)`; no annualization inside the pipeline.

**Evaluation protocol:**
- Walk-forward expanding window: min_train=252 (≈1 year), step=21 (≈1 month).
- Metrics are computed only on walk-forward **test** indices — no in-sample leakage.
- NaN target rows (final `horizon` rows per series) are dropped before scoring.
- Zero target rows (identical consecutive closes — yfinance adjusted-close artifact)
  are also dropped (a zero realized variance causes QLIKE = +inf via log(0)).
- EWMA lambda = 0.94 (RiskMetrics daily, J.P. Morgan 1994).

**Status:** EWMA baseline only.  GARCH(1,1) and HAR-RV are added in Plan 02-03.

---

"""


@dataclass
class _AssetResult:
    """Intermediate result for one asset's walk-forward evaluation."""

    slug: str
    model: str
    n_forecasts: int
    rmse_val: float
    mae_val: float
    qlike_val: float


def generate_baseline_report(
    assets: list[dict[str, Any]],
    output_dir: Path,
    min_train: int = 252,
    step: int = 21,
    data_root: Path | None = None,
) -> Path:
    """Run EWMA walk-forward evaluation and write baseline_eval.md + baseline_metrics.csv.

    For each asset in ``assets``:
    1. Load the processed parquet from ``config.processed_path(asset, data_root)``.
    2. Compute log returns and the next-day realized-variance target.
    3. Generate one-step-ahead EWMA forecasts for the full series.
    4. Iterate ``walk_forward_splits(n, min_train, step, horizon=HORIZON)``
       collecting forecast/target pairs at every test index across all folds.
    5. Drop pairs where the target is NaN (end-of-series — Pitfall 4).
    6. Score the collected pairs with ``qlike``, ``rmse``, ``mae``.

    Both output files are written atomically (write to tmp name, rename) to
    prevent partial-file reads if the process is interrupted.

    Args:
        assets:     List of asset dicts with keys ``symbol`` and ``asset_class``.
                    Each dict is passed directly to ``config.symbol_slug`` and
                    ``config.processed_path``.
        output_dir: Directory to write ``baseline_eval.md`` and
                    ``baseline_metrics.csv``.  Created if it does not exist.
        min_train:  Minimum training window size for the harness.  Default 252.
        step:       Walk-forward step and test window size.  Default 21.
        data_root:  Data root directory passed to ``config.processed_path``.
                    If None, defaults to ``config.project_root() / "data"``.

    Returns:
        Path to the written ``baseline_eval.md``.

    Raises:
        FileNotFoundError: If a processed parquet does not exist for an asset.
        ValueError: If no valid forecast/target pairs are found for any asset
                    (series too short for min_train).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results: list[_AssetResult] = []

    for asset in assets:
        slug = cfg.symbol_slug(asset["symbol"])
        parquet_path = cfg.processed_path(asset, data_root)

        log.info("Evaluating EWMA baseline for %s (%s)", slug, parquet_path)

        df = pd.read_parquet(parquet_path)
        close = df["close"].rename(slug)

        # Compute log returns and target (decimal variance proxy)
        lr = log_returns(close)
        target = compute_target(close, horizon=HORIZON)

        n = len(close)

        # EWMA one-step-ahead forecast for the full series (no per-fold refit needed)
        model = EWMA()
        forecasts = model.forecast_path(lr)

        # Collect forecast/target pairs across all walk-forward test folds
        all_forecasts: list[float] = []
        all_targets: list[float] = []

        for split in walk_forward_splits(n, min_train=min_train, step=step, horizon=HORIZON):
            test_fc = forecasts.iloc[split.test_idx]
            test_tgt = target.iloc[split.test_idx]

            # Pitfall 4: drop NaN targets — never fill with zero.
            # Also drop exact-zero targets: target = squared log return == 0 means
            # identical consecutive closes (yfinance adjusted-close artifact).
            # A zero realized variance causes QLIKE = +inf (log(0) = -inf).
            valid_mask = test_tgt.notna() & (test_tgt > 0.0)
            if valid_mask.any():
                all_forecasts.extend(test_fc[valid_mask].tolist())
                all_targets.extend(test_tgt[valid_mask].tolist())

        if not all_forecasts:
            log.warning(
                "Asset %s: no valid forecast/target pairs collected "
                "(series length=%d, min_train=%d) — skipping",
                slug,
                n,
                min_train,
            )
            continue

        n_fc = len(all_forecasts)
        rmse_val = rmse(all_targets, all_forecasts)
        mae_val = mae(all_targets, all_forecasts)
        qlike_val = qlike(all_targets, all_forecasts)

        log.info(
            "%s EWMA: n=%d  RMSE=%.6e  MAE=%.6e  QLIKE=%.6f",
            slug,
            n_fc,
            rmse_val,
            mae_val,
            qlike_val,
        )

        results.append(
            _AssetResult(
                slug=slug,
                model="EWMA",
                n_forecasts=n_fc,
                rmse_val=rmse_val,
                mae_val=mae_val,
                qlike_val=qlike_val,
            )
        )

    if not results:
        raise ValueError(
            "No assets produced valid results.  Check that series are long enough "
            f"for min_train={min_train} and step={step}."
        )

    # ------------------------------------------------------------------ #
    # Write Markdown table
    # ------------------------------------------------------------------ #
    md_path = output_dir / "baseline_eval.md"
    _write_markdown(results, md_path)

    # ------------------------------------------------------------------ #
    # Write CSV
    # ------------------------------------------------------------------ #
    csv_path = output_dir / "baseline_metrics.csv"
    _write_csv(results, csv_path)

    log.info("Baseline report written to %s", output_dir)
    return md_path


def _write_markdown(results: list[_AssetResult], path: Path) -> None:
    """Write the per-asset metrics table as a Markdown file."""
    lines = [_REPORT_HEADER]
    lines.append("## Per-Asset Metrics\n")
    lines.append("\n")
    lines.append("| Asset | Model | N Forecasts | RMSE | MAE | QLIKE |\n")
    lines.append("|-------|-------|-------------|------|-----|-------|\n")

    for r in results:
        lines.append(
            f"| {r.slug} | {r.model} | {r.n_forecasts:,} "
            f"| {r.rmse_val:.6e} | {r.mae_val:.6e} | {r.qlike_val:.6f} |\n"
        )

    lines.append("\n")
    lines.append("---\n")
    lines.append(
        "*Metrics: daily decimal variance units. "
        "QLIKE = 0 at perfect forecast. "
        "GARCH(1,1) and HAR-RV baselines added in Plan 02-03.*\n"
    )

    # Atomic write
    tmp = path.with_suffix(".tmp")
    tmp.write_text("".join(lines), encoding="utf-8")
    tmp.replace(path)


def _write_csv(results: list[_AssetResult], path: Path) -> None:
    """Write the per-asset metrics as a CSV file."""
    fieldnames = ["asset", "model", "n_forecasts", "rmse", "mae", "qlike"]

    # Atomic write
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            writer.writerow(
                {
                    "asset": r.slug,
                    "model": r.model,
                    "n_forecasts": r.n_forecasts,
                    "rmse": f"{r.rmse_val:.10e}",
                    "mae": f"{r.mae_val:.10e}",
                    "qlike": f"{r.qlike_val:.10f}",
                }
            )
    tmp.replace(path)
